### ISSUE TITLE
Regarding the issue of custom tasks

### ISSUE THREAD

**Issue by pixeli99** [ucd-dare/CarDreamer#13]
This is truly an excellent work, many thanks for the author's effort.

As a beginner, I would like to know how to customize a scene, for example, how can I train with the scene in `https://github.com/carla-simulator/leaderboard/tree/leaderboard-2.0` in cardreamer, does the author have any simple suggestions?

**Comment by gaodechen** [comment]
Thank you for your interests and comments!

It is a good idea to integrate Leaderboard scenarios for WM training, but for now CarDreamer has its own APIs to support customization, and the built-in tasks are also quite different. So we would suggest choosing one based on your purposes

* Leaderboard has very challenging and complicated built-in scenarios which are defined as a tree structure using `py_tress` and atomic traffic behaviors. This workflow was supproted by `scenario_runner`. So for customization, you need to define what happened under which conditions and so on. Check out this example yaml for a route-based scenario definition [routes_training.xml](https://github.com/carla-simulator/leaderboard/blob/leaderboard-2.0/data/routes_training.xml). People have been using expert demonstrations collected along these training routes to train self-driving agents for Leaderboard.
* CarDreamer built-in tasks are less granular traffic behaviors like left, right turns, or traffic light handling. The models in our paper are doing online learning from scratch rather than using expert demonstrations. CarDreamer is lightweight for customization and training. Check out an example here [carla_four_lane](https://github.com/ucd-dare/CarDreamer/blob/master/car_dreamer/carla_four_lane_env.py) and [tasks.yaml](https://github.com/ucd-dare/CarDreamer/blob/5b28b7ffa5ee90fdddd5cff95cfeda56afd99a62/car_dreamer/configs/tasks.yaml#L36). We have also integrated gym interfaces with an empirically optimized rewards which can be friendly for RL. So you can see it is quite different compared to Leaderboard in terms of scenario customization and use cases.

Hope this helps and let me know if you have further questions

**Comment by pixeli99** [comment]
Thank you very much for your reply,

I roughly understand the differences you mentioned, possibly because I am a beginner and still unfamiliar with some of the details.

To summarize, my question is, if I want to train `dreamerv3` in such a complex scenario as provided by the leaderboard, should I base it on `cardreamer`?

As far as I understand, `scenario_runner` provides users with a flexible way to create complex driving scenarios. I am not quite sure whether this concept is similar to the ENV concept of cardreamer? What I mean is, what kind of work would roughly be required to integrate a complex scenario **from scenario_runner into CarDreamer**?

I hope to get some of your suggestions.

**Comment by gaodechen** [comment]
Hi!

1. "... if I want to train dreamerv3 in such a complex scenario as provided by the leaderboard, should I base it on cardreamer?"

No, you need to wrap up `scenario_runner` with a gym interface to train `dreamerv3` on Leaderboard.

2. "scenario_runner provides users with a flexible way to create complex driving scenarios. I am not quite sure whether this concept is similar to the ENV concept of cardreamer?"

The concept of a scenario in Leaderboard is similar an ENV in CarDreamer. But Leaderboard is based on `scenario_runner` APIs; CarDreamer uses it own and it has a gym wrapper. To create new tasks in CarDreamer, you can either

* Instantitate an ENV such as `right_turn` with different parameters including traffic density, speed, etc., such that the background traffic or rewards are different but it is still in essence a `right_turn` task.
*  If the built-in tasks do not include tasks you need, you can create a new ENV with the your own task design, including how you want the background traffic flow works, or what multi-modal observations should be used, and what kind of routes you expect the ego vehicle to follow.

3. what kind of work would roughly be required to integrate a complex scenario from scenario_runner into CarDreamer?

The way CarDreamer defines and executes tasks are very different from `scenario_runner` and they kinda serve different purposes. Given this, if you want to train Dreamer on Leaderboard, it might be easier to make separate gym interfaces for `scenario_runner` rather than put them altogether.

Hope this helps!

**Comment by pixeli99** [comment]
Thank you so much for such detailed suggestions.
At the same time, I would like to express my gratitude once again to the author for their excellent work!
